# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/jwt/jwt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoc_gen_swagger.options import annotations_pb2 as protoc__gen__swagger_dot_options_dot_annotations__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/jwt/jwt.proto',
  package='jwt',
  syntax='proto3',
  serialized_options=_b('\222A\334\006\022\213\001\n#The title of Authentication service\"]\n\026Authentication project\022)https://tech.dzones.vn/api/authentication\032\030loc.truong.huu@dzones.vn2\0051.1.0*\003\001\002\0042\020application/json2\026application/x-foo-mime:\020application/json:\026application/x-foo-mimeRP\n\003403\022I\nGReturned when the user does not have permission to access the resource.R;\n\003404\0224\n*Returned when the resource does not exist.\022\006\n\004\232\002\001\007RH\n\003418\022A\n\rI\'m a teapot.\0220\n.\032,.grpc.gateway.examples.examplepb.NumericEnumZ\211\002\n\017\n\tBasicAuth\022\002\010\001\n\035\n\nApiKeyAuth\022\017\010\002\032\tX-API-Key \002\n\326\001\n\006OAuth2\022\313\001\010\003(\0042#https://example.com/oauth/authorize:\037https://example.com/oauth/tokenB\177\n\032\n\004read\022\022Grants read access\n\034\n\005write\022\023Grants write access\nC\n\005admin\022:Grants read and write access to administrative informationb\037\n\r\n\tBasicAuth\022\000\n\016\n\nApiKeyAuth\022\000b)\n\027\n\006OAuth2\022\r\n\004read\n\005write\n\016\n\nApiKeyAuth\022\000rB\n\031More about Authentication\022%https://docs.dzones.vn/authentication'),
  serialized_pb=_b('\n\x13proto/jwt/jwt.proto\x12\x03jwt\x1a,protoc-gen-swagger/options/annotations.proto\x1a\x1cgoogle/api/annotations.proto\"\x1d\n\x0c\x41nnouncement\x12\r\n\x05title\x18\x01 \x01(\t\"\x18\n\x07Request\x12\r\n\x05token\x18\x01 \x01(\t\")\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t2\x91\x01\n\nJWTService\x12@\n\x06Verify\x12\x0c.jwt.Request\x1a\r.jwt.Response\"\x19\x82\xd3\xe4\x93\x02\x13\"\x0e/v1/jwt/verify:\x01*\x12\x41\n\x04\x45\x63ho\x12\x0c.jwt.Request\x1a\r.jwt.Response\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/jwt/echo/{token}B\xe0\x06\x92\x41\xdc\x06\x12\x8b\x01\n#The title of Authentication service\"]\n\x16\x41uthentication project\x12)https://tech.dzones.vn/api/authentication\x1a\x18loc.truong.huu@dzones.vn2\x05\x31.1.0*\x03\x01\x02\x04\x32\x10\x61pplication/json2\x16\x61pplication/x-foo-mime:\x10\x61pplication/json:\x16\x61pplication/x-foo-mimeRP\n\x03\x34\x30\x33\x12I\nGReturned when the user does not have permission to access the resource.R;\n\x03\x34\x30\x34\x12\x34\n*Returned when the resource does not exist.\x12\x06\n\x04\x9a\x02\x01\x07RH\n\x03\x34\x31\x38\x12\x41\n\rI\'m a teapot.\x12\x30\n.\x1a,.grpc.gateway.examples.examplepb.NumericEnumZ\x89\x02\n\x0f\n\tBasicAuth\x12\x02\x08\x01\n\x1d\n\nApiKeyAuth\x12\x0f\x08\x02\x1a\tX-API-Key \x02\n\xd6\x01\n\x06OAuth2\x12\xcb\x01\x08\x03(\x04\x32#https://example.com/oauth/authorize:\x1fhttps://example.com/oauth/tokenB\x7f\n\x1a\n\x04read\x12\x12Grants read access\n\x1c\n\x05write\x12\x13Grants write access\nC\n\x05\x61\x64min\x12:Grants read and write access to administrative informationb\x1f\n\r\n\tBasicAuth\x12\x00\n\x0e\n\nApiKeyAuth\x12\x00\x62)\n\x17\n\x06OAuth2\x12\r\n\x04read\n\x05write\n\x0e\n\nApiKeyAuth\x12\x00rB\n\x19More about Authentication\x12%https://docs.dzones.vn/authenticationb\x06proto3')
  ,
  dependencies=[protoc__gen__swagger_dot_options_dot_annotations__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_ANNOUNCEMENT = _descriptor.Descriptor(
  name='Announcement',
  full_name='jwt.Announcement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='jwt.Announcement.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=133,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='jwt.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='jwt.Request.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=159,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='jwt.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='jwt.Response.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='jwt.Response.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=202,
)

DESCRIPTOR.message_types_by_name['Announcement'] = _ANNOUNCEMENT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Announcement = _reflection.GeneratedProtocolMessageType('Announcement', (_message.Message,), dict(
  DESCRIPTOR = _ANNOUNCEMENT,
  __module__ = 'proto.jwt.jwt_pb2'
  # @@protoc_insertion_point(class_scope:jwt.Announcement)
  ))
_sym_db.RegisterMessage(Announcement)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'proto.jwt.jwt_pb2'
  # @@protoc_insertion_point(class_scope:jwt.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'proto.jwt.jwt_pb2'
  # @@protoc_insertion_point(class_scope:jwt.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_JWTSERVICE = _descriptor.ServiceDescriptor(
  name='JWTService',
  full_name='jwt.JWTService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=205,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='Verify',
    full_name='jwt.JWTService.Verify',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=_b('\202\323\344\223\002\023\"\016/v1/jwt/verify:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='jwt.JWTService.Echo',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=_b('\202\323\344\223\002\026\022\024/v1/jwt/echo/{token}'),
  ),
])
_sym_db.RegisterServiceDescriptor(_JWTSERVICE)

DESCRIPTOR.services_by_name['JWTService'] = _JWTSERVICE

# @@protoc_insertion_point(module_scope)
